### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by josephgupkim** [Fendavo/jammming#3]
Upon reviewing your project, I can confidently say that all necessary functionalities seem to be present and working flawlessly.

- Connecting to Spotify.
- Searching a song.
- Relevant results appear.
- Can add/remove songs to playlist.

**Comment by Fendavo** [comment]
Yes, thank you, but I was not happy with the fact that I had to search twice. Not sure what happens the first time, but to reproduce the problem, simply search and notice that results are empty. Repeat the exact search and suddenly the results are there. I will look at it again to see why, but right now I have no idea.
