### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by josephgupkim** [Fendavo/jammming#4]
This Jamming project proved that your knowledge of the curriculum material so far is present. Your coding abilities and logic made for an amazing Jamming project that looked great on the code side while performing smoothly on the interactive web/user side. Awesome work!

- Utilization of indentations and whitespace.
- Sound code logic.
- Desired functionalities present.

Keep up the superb job!
Grade: Meets expectation

**Comment by Fendavo** [comment]
Thank you, but I feel a but like I created it with a "monkey see, monkey do" approach. I have coded in many languages, but this is testing me.
