### ISSUE TITLE
Feature Request: Summary

### ISSUE THREAD

**Issue by SidTheEngineer** [Fendavo/jammming#5]
## Objective/Background

> Netflix acknowledges that artwork is a big attractor to an audience and they note that short attention spans are held momentarily by images. That seems to be a valid reason for including thumbnails on the Jammming search results. https://www.theverge.com/2016/5/3/11582382/netflix-thumbnail-test. 

Great research point here! Overall, I think this is a great addition to the app and your justification is perfect. Good work 👍 

## Technical Design

> The prop can be dropped into an img tag that will need to be added to the Track.js component, render() method. 

Perfect way to do this here 👍. Overall, I think your technical design is spot on. This is the most straightforward and intuitive way to implement this feature.

## Caveats

> It is possible that album cover art could be unavailable for a track, which may cause the visible data to become misaligned. To mitigate this, a decision statement could be added so that if no image url is detected in the third element of the array, then a ‘dummy’ no-image.png be substituted for the url.

Awesome! This is definitely an edge case that can be addressed. Having a placeholder image is a good way to do this so as to keep the UI consistent.

## Overall

Looks like you've nailed this feature request 👍. The write up was great and execution worked as expected. This is definitely a nice feature to have. Great work

**Comment by Fendavo** [comment]
Thanks heaps Sid, for your positive feedback.
Cheers
